# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='Thread', max_length=255),
            preserve_default=False,
        ),
    ]
