# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.TextField(max_length=255),
        ),
    ]
