# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160917_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
