# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
    ]
