# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_auto_20160916_0852'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('token', models.TextField(default=uuid.uuid4, max_length=100, unique=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
            ],
        ),
    ]
