# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20151231_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
