# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'bands')),
                ('primary', models.BooleanField(default=False)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
            ],
        ),
    ]
