---
 - hosts: digital-ocean
   vars:
     date: "{{ ansible_date_time.date }}"
     tar: /tmp/{{ tar_name }}
     deploy_path: "/srv/bandalists"
     venv: /opt/venvs/bandalists

   tasks:
     - name: Create User
       user: name=bandalists group=www-data

     - name: 'include vault'
       include_vars: vault.yml

     - name: Install required packages
       apt: name={{ item }}
       with_items:
        - python-pip
        - python-dev
        - libjpeg-dev
        - python-psycopg2
        - lib32ncurses5-dev
        - postgresql
        - postgresql-server-dev-all
        - postgresql-client
        - nginx
        - uwsgi
        - uwsgi-plugin-python
        - redis-server

     - name: Install virtualenv
       pip: name={{ item }}
       with_items:
         - virtualenv

     - name: Ensure the PostgreSQL service is running
       service: name=postgresql state=started enabled=yes
       tags:
         - db

     - postgresql_db: name=bandalists
       become_user: postgres
       become: yes
       tags:
         - db

     - postgresql_user: name=root
       become_user: postgres
       become: yes
       tags:
         - db

     - postgresql_user: db=bandalists name=bandalists
       become_user: postgres
       become: yes
       tags:
         - db

     - postgresql_user: db=bandalists name=bandalists
       become_user: postgres
       become: yes
       tags:
         - db

     - git:
         repo: 'https://github.com/kroustou/bandalists.git'
         dest: '{{ deploy_path }}'

     - name: Change ownership
       file: path={{ deploy_path }} state=directory owner=bandalists recurse=yes

     - name: Create venv
       pip: requirements={{ deploy_path }}/bandalists_drf/requirements.txt virtualenv={{ venv }}

     - name: Copy local settings
       template: src=templates/local_settings.py.j2 dest={{ deploy_path }}/bandalists_drf/bandalists_drf/local_settings.py

     - django_manage: command=migrate app_path="{{ deploy_path }}/bandalists_drf" virtualenv={{ venv }}
       become_user: bandalists
       become: yes
       tags:
         - manage

     - name: Set up nginx
       template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/bandalists
       tags:
         - manage

     - file: src='/etc/nginx/sites-available/bandalists' dest='/etc/nginx/sites-enabled/bandalists' state=link
       tags:
         - manage

     - name: Copy daphne init script
       template: src=templates/daphne.service.j2 dest=/etc/systemd/system/bandalists.service

     - name: Copy worker init script
       template: src=templates/worker.service.j2 dest=/etc/systemd/system/bandalists-worker.service

     - name: restart nginx
       service: name=nginx state=restarted enabled=yes
       tags:
         - manage

     - name: Make sure the service is running
       systemd: state=started name=bandalists daemon-reload=yes


